version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
  file:
    class: logging.FileHandler
    filename: logs/app.log
    formatter: simple
    level: INFO
loggers:
  prediction_engine:
    handlers: [console, file]
    level: DEBUG
